title: AI & Software Development Blog
description: News and insights about AI and software development
author: Priscila Saboia Moreira
baseurl: "/aiblog" # the subpath of your site
url: "https://psaboia.github.io" # the base hostname & protocol

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Google Analytics
google_analytics: "G-DN4VL9R9W0" # Replace with your Google Analytics measurement ID (G-XXXXXXXXXX)

# Disqus Comments
disqus:
  # Replace EXAMPLE with your Disqus shortname
  shortname: aiblog-prisaboia

# Default settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true

# Force rebuild comment
# Last updated: 2024-04-03 12:00
